name: simple_secure_storage
repository: https://github.com/Skyost/SimpleSecureStorage

packages:
  - packages/*
  - packages/simple_secure_storage/example

command:
  version:
    linkToCommits: true
    branch: main
    workspaceChangelog: false
    hooks:
      pre: dart format "packages/simple_secure_storage/lib" && melos analyze
    message: |
      chore(release): Publish packages.

      {new_package_versions}

scripts:
  analyze:
    exec: dart analyze .