name: simple_secure_storage
description: "Simple and secure storage for Flutter."
version: 0.0.1
homepage: https://github.com/Skyost/SimpleSecureStorage

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  dbus: ^0.7.10
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        package: fr.skyost.simple_secure_storage
        pluginClass: SimpleSecureStoragePlugin
      ios:
        pluginClass: SimpleSecureStoragePlugin
        sharedDarwinSource: true
      linux:
        pluginClass: SimpleSecureStorageLinux
        fileName: src/implementations/linux.dart
      macos:
        pluginClass: SimpleSecureStoragePlugin
        sharedDarwinSource: true
      windows:
        pluginClass: SimpleSecureStoragePluginCApi
      web:
        pluginClass: SimpleSecureStorageWeb
        fileName: src/implementations/web.dart
