name: simple_secure_storage_android
description: Android implementation of the SimpleSecureStorage plugin.
homepage: https://github.com/Skyost/SimpleSecureStorage
repository: https://github.com/Skyost/SimpleSecureStorage/tree/master/packages/simple_secure_storage_android
issue_tracker: https://github.com/Skyost/SimpleSecureStorage/issues
version: 0.0.1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

flutter:
  plugin:
    platforms:
      implements: simple_secure_storage
      android:
        package: fr.skyost.simple_secure_storage
        pluginClass: SimpleSecureStoragePlugin

dependencies:
  flutter:
    sdk: flutter
  simple_secure_storage_platform_interface: ^0.0.1

dependency_overrides:
  simple_secure_storage_platform_interface:
    path: ../simple_secure_storage_platform_interface/
